services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports: ["3306:3306"]
    volumes: ["mysql_data:/var/lib/mysql"]
    restart: unless-stopped
    profiles: ["infra","all"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped
    profiles: ["infra","all"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms768m -Xmx768m
    ports: ["9200:9200"]
    volumes: ["es_data:/usr/share/elasticsearch/data"]
    restart: unless-stopped
    profiles: ["infra","all"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: ["5601:5601"]
    depends_on: ["elasticsearch"]
    restart: unless-stopped
    profiles: ["infra","all"]

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.0
    user: root
    command: ["--strict.perms=false"]
    depends_on: ["elasticsearch"]
    volumes:
      - ./logs:/app-logs:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    restart: unless-stopped
    profiles: ["infra","all"]

  app:
    build: .
    ports: ["8080:8080"]
    depends_on: ["mysql","redis","elasticsearch"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_REDIS_HOST: redis
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.keys_under_root: "true"
      co.elastic.logs/json.add_error_key: "true"
    restart: unless-stopped
    profiles: ["all"]

volumes:
  mysql_data:
  es_data:
