spring:
  profiles:
    active: local

  datasource:
    # local 환경에서는 DB를 미리 띄운상태에서 localhost로 접속
    url: jdbc:mysql://localhost:3306/bookdb?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    uris: http://localhost:9200

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b %D ms %{X-Request-Id}i"
      directory: logs
