{
 "title": "Spring Boot Essentials",
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": "label_values(http_server_requests_seconds_count, application)"
   },
   {
    "name": "env",
    "query": "label_values(http_server_requests_seconds_count, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{outcome=~\"CLIENT_ERROR|SERVER_ERROR\"}[1m])) / sum(rate(http_server_requests_seconds_count[1m])))*100"
    }
   ]
  },
  {
   "title": "HTTP P95 Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "JVM Heap Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"})) * 100"
    }
   ]
  },
  {
   "title": "Tomcat Busy Threads (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(tomcat_threads_busy) / sum(tomcat_threads_current)) * 100"
    }
   ]
  },
  {
   "title": "Hikari Active / Max (connections)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active)"
    },
    { "expr": "sum(hikaricp_connections)" }
   ]
  },
  {
   "title": "Process CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "avg(process_cpu_usage) * 100" }
   ]
  },
  {
   "title": "JVM Threads Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "sum(jvm_threads_live)" }
   ]
  }
 ]
}